[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.llamahub]
contains_example = true
import_path = "llama_index.readers.gutenberg"

[tool.llamahub.class_authors]
ProjectGutenbergReader = "Oguz Vuruskaner"

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.8"

[tool.poetry]
authors = ["ovuruska <oguzvuruskaner@gmail.com>"]
description = "llama-index readers gutenberg integration ebook"
exclude = ["**/BUILD"]
license = "MIT"
maintainers = ["ovuruska"]
name = "llama-index-readers-gutenberg"
readme = "README.md"
version = "0.0.1"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
llama-index-core = "^0.10.1"

[tool.poetry.group.dev.dependencies]
types-requests = "2.28.11.8"

[tool.poetry.group.dev.dependencies.black]
extras = ["jupyter"]
version = "<=23.9.1,>=23.7.0"

[tool.poetry.group.dev.dependencies.codespell]
extras = ["toml"]
version = ">=v2.2.6"

[[tool.poetry.packages]]
include = "llama_index/"
